version: '2.1'
services:
    postgres:
        image: postgres:9.6
        container_name: af_postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata
        ports:
            - 25432:5432

    webserver:
        extends:
            file: docker-compose.airflow.local.yml
            service: airflow
        container_name: af_webserver
        command: webserver
        depends_on:
            - postgres
        ports:
            - 28080:8080
#        networks:
#            - proxy
#            - default
        environment:
            - TZ=Asia/Shanghai
            - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Shanghai
            - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=Asia/Shanghai
#            # Web Server Config
#            - AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW=graph
#            - AIRFLOW__WEBSERVER__HIDE_PAUSED_DAGS_BY_DEFAULT=true
#            - AIRFLOW__WEBSERVER__RBAC=true
#
#            # Web Server Performance tweaks
#            # 2 * NUM_CPU_CORES + 1
#            - AIRFLOW__WEBSERVER__WORKERS=5
#            # Restart workers every 30min instead of 30seconds
#            - AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL=1800
#        labels:
#            - "traefik.enable=true"
#            - "traefik.http.routers.airflow.rule=Host(`af.example.com`)"
#            - "traefik.http.routers.airflow.middlewares=admin-auth@file"
        healthcheck:
            test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    scheduler:
        extends:
            file: docker-compose.airflow.local.yml
            service: airflow
        container_name: af_scheduler
        command: scheduler
        depends_on:
            - postgres
        ports:
            - 28081:8080
        environment:
            - TZ=Asia/Shanghai
            - AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Shanghai
            - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=Asia/Shanghai
#        environment:
#            # Performance Tweaks
#            # Reduce how often DAGs are reloaded to dramatically reduce CPU use
#            - AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL=${AF_MIN_FILE_PROCESS_INTERVAL-60}
#            - AIRFLOW__SCHEDULER__MAX_THREADS=${AF_THREADS-1}

#networks:
#    proxy:
#        external: true
